# Generated by Django 6.0 on 2025-12-20 13:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_adminuser_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adminuser",
            name="username",
            field=models.CharField(
                max_length=150, unique=True, verbose_name="Username"
            ),
        ),
    ]
